# 키 날아가면,
# docker exec -it sermon cat /root/.ssh/id_rsa.pub

# rtd cjng96
# vi .ssh/authorized_keys

# 서버 재설치시
# sudo yum install python3-devel
# sudo pip3 install wheel psutil

port: 25090
domain: watchmon.retailtrend.net
name: Earlgrey monitoring
fixedFont: true

notification:
  type: gmail
  id: cjng96@gmail.com
  pw:
  emails:
    - cjng96@gmail.com

servers1:
  - name: motionFilter
    url: 52.9.57.155
    id: centos
    monitor:
      - load
      - mem
      - swap
      - disk
      - { type: disk, name: ftp, path: /var/ftp }

servers:
  - name: tool
    url: sermon.retailtrend.net:443
    id: ubuntu
    monitor:
      # - cpu
      - load
      - mem
      - swap
      - disk
      - { type: app, name: dataMon, status: /tmp/dataMon-prod.st }

  - name: retailtrend
    url: retailtrend.net
    id: cjng96
    monitor:
      # - cpu
      - load
      - mem
      - swap
      - disk
      - { type: disk, name: mongo, path: /var/lib/mongo }
      # - { type: disk, name: maria, path: /var/lib/mysql }
      - { type: disk, name: retrache, path: /mnt/retrache }
      - { type: app, name: dbapi, status: /tmp/dbapi.st }
      - { type: app, name: dxm, status: /tmp/dxm.st }
      - { type: app, name: fotaSer, status: /tmp/fotaServer.st }
      - { type: app, name: retrache, status: /tmp/retrache.st }
      - { type: app, name: trackIo, status: /tmp/track-io.st }
      - { type: app, name: exportData, status: /tmp/cron.exportdata.st }

  - name: develop
    url: dev.retailanalysis.cloud
    id: cjng96
    monitor:
      # - cpu
      - load
      - mem
      - swap
      - disk
      - { type: disk, name: mongo, path: /var/lib/mongo }
      - { type: disk, name: maria, path: /var/lib/mysql }
      - { type: disk, name: retrache, path: /mnt/retrache }
      - { type: app, name: dbapi, status: /tmp/dbapi.st }
      - { type: app, name: dxm, status: /tmp/dxm.st }
      - { type: app, name: fotaSer, status: /tmp/fotaServer.st }
      - { type: app, name: retrache, status: /tmp/retrache.st }
      - { type: app, name: trackIo, status: /tmp/track-io.st }
      - { type: app, name: exportData, status: /tmp/cron.exportdata.st }

  - name: motionFilter
    url: 52.9.57.155
    id: centos
    key: key/id_ed25519
    monitor:
      - load
      - mem
      - swap
      - disk
      - { type: disk, name: ftp, path: /var/ftp }
      - { type: app, name: motionFilter, status: /tmp/motion_filter.st }

  - name: secure
    url: secure.retailtrend.net
    id: cjng96
    monitor:
      # - cpu
      - load
      - mem
      - swap
      - disk
      - { type: app, name: reportMsgT, status: /work/msgt/app.st }
      - { type: app, name: reportMsg, status: /work/msg/app.st }
      - { type: app, name: faceTracerT, status: /work/ftt/app.st }
      - { type: app, name: faceTracer, status: /work/ft/app.st }

  - name: report
    url: 54.151.14.237
    id: cjng96
    monitor:
      - load
      - mem
      - swap
      - disk
      - { type: app, name: excel, status: /mnt/c/work/excel.st }
