port: 25090
domain: watchmon.ucount.it

notification:
  type: gmail
  id: cjng96@gmail.com
  pw:
  emails:
    - cjng96@gmail.com

servers:
  - name: rtw
    url: watchmon.ucount.it:443
    id: ubuntu
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
