port: 25090
domain: sermon.mmx.kr

notification:
  type: gmail
  id: cjng96@gmail.com
  pw:
  emails:
    - cjng96@gmail.com

servers:
  - name: tk1
    url: tk1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
      - { type: app, name: eng, status: /work/eng/eng.st }
      - { type: app, name: engT, status: /work/engt/engt.st }
      - { type: app, name: inerAuth, status: /work/iauth/inerAuth.st }
      - { type: app, name: inerAuthT, status: /work/iautht/inerAuthT.st }
      - { type: app, name: inerUpdate, status: /work/iupdate/inerUpdate.st }
      - { type: app, name: inerUpdateT, status: /work/iupdatet/inerUpdateT.st }
      - { type: app, name: engFile, status: /work/efile/engFile.st }
      - { type: app, name: engFileT, status: /work/efilet/engFileT.st }

  - name: nj1
    url: nj1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk

  - name: aws1
    url: aws1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk

  - name: aws1/coll
    url: aws1.inertry.com
    id: cjng96
    dkName: colls
    dkId: cjng96
    monitor:
      - { type: app, name: coll, status: /tmp/coll.st }
      - { type: app, name: collT, status: /tmp/collT.st }
      - { type: app, name: collPlus, status: /tmp/collPlus.st }
      - { type: app, name: collPlusT, status: /tmp/collPlusT.st }
      - { type: app, name: inerLog, status: /tmp/inerLog.st }
      - { type: app, name: inerLogT, status: /tmp/inerLogT.st }
      - { type: app, name: collAdmin, status: /tmp/collAdmin.st }

  - name: n2
    url: nas.mmx.kr:7022
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
