port: 25090
domain: watchmon.ucount.it

notification:
  type: gmail
  id: cjng96@gmail.com
  pw:
  emails:
    - cjng96@gmail.com

servers:
  - name: watchmon
    url: watchmon.ucount.it:443
    id: ubuntu
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk

  - name: retailtrend
    url: retailtrend.net
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
