
servers:
  - name: tk1
    url: tk1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - mem
      - disk

  - name: engs
    url: tk1.synapbook.com
    id: cjng96
    dkName: engs
    dkId: cjng96
    monitor:
      - { type: app, name: eng, status: /tmp/engt.st }

  - name: nj1
    url: nj1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - mem
      - disk
  
notification:
 - cjng96@gmail.com

port: 25090
