port: 25090
domain: sermon.mmx.kr

notification:
  type: gmail
  id: cjng96@gmail.com
  pw:
  emails:
    - cjng96@gmail.com

servers:
  - name: tk1
    url: tk1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
      - { type: app, name: eng, status: /data/eng/tmp/eng.st }
      - { type: app, name: engT, status: /data/engt/tmp/engt.st }
      - { type: app, name: inerAuth, status: /data/iauth/tmp/inerAuth.st }
      - { type: app, name: inerAuthT, status: /data/iautht/tmp/inerAuthT.st }
      - { type: app, name: inerUpdate, status: /data/iupdate/tmp/inerUpdate.st }
      - {
          type: app,
          name: inerUpdateT,
          status: /data/iupdatet/tmp/inerUpdateT.st,
        }
      - { type: app, name: engFile, status: /data/efile/tmp/engFile.st }
      - { type: app, name: engFileT, status: /data/efilet/tmp/engFileT.st }
      - { type: app, name: coll, status: /data/coll/tmp/coll.st }
      - { type: app, name: collT, status: /data/collt/tmp/collT.st }
      - { type: app, name: collPlus, status: /data/collplus/tmp/collPlus.st }
      - { type: app, name: collPlusT, status: /data/collplust/tmp/collPlusT.st }
      - { type: app, name: inerLog, status: /data/ilog/tmp/inerLog.st }
      - { type: app, name: inerLogT, status: /data/ilogt/tmp/inerLogT.st }
      - { type: app, name: collAdmin, status: /data/collAdmin/tmp/collAdmin.st }

  - name: aws1
    url: aws1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk

  - name: n2
    url: nas.mmx.kr:7022
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
