
port: 25090
domain: sermon.mmx.kr

notification:
  type: gmail
  id: cjng96@gmail.com
  pw: 
  emails: 
    - cjng96@gmail.com

servers:
  - name: tk1
    url: tk1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk

  - name: tks
    url: tk1.inertry.com
    id: cjng96
    dkName: engs
    dkId: cjng96
    monitor:
      - { type: app, name: eng, status: /tmp/eng.st }
      - { type: app, name: engT, status: /tmp/engt.st }
      - { type: app, name: inerAuth, status: /tmp/inerAuth.st }
      - { type: app, name: inerAuthT, status: /tmp/inerAuthT.st }
      - { type: app, name: inerUpdate, status: /tmp/inerUpdate.st }
      - { type: app, name: inerUpdateT, status: /tmp/inerUpdateT.st }

  - name: nj1
    url: nj1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
  
  - name: njf
    url: nj1.inertry.com
    id: cjng96
    dkName: efile
    dkId: cjng96
    monitor:
      - { type: app, name: engFile, status: /tmp/engFile.st }
      - { type: app, name: engFileT, status: /tmp/engFileT.st }
    
  - name: aws1
    url: aws1.inertry.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
      
  - name: aws1/coll
    url: aws1.inertry.com
    id: cjng96
    dkName: coll
    dkId: cjng96
    monitor:
      - { type: app, name: coll, status: /tmp/coll.st }
      - { type: app, name: collT, status: /tmp/collT.st }
      - { type: app, name: collPlus, status: /tmp/collPlus.st }
      - { type: app, name: collPlusT, status: /tmp/collPlusT.st }
      - { type: app, name: inerLog, status: /tmp/inerLog.st }
      - { type: app, name: inerLogT, status: /tmp/inerLogT.st }
      - { type: app, name: collAdmin, status: /tmp/collAdmin.st }
        
  - name: n2
    url: nas.mmx.kr:7022
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
    
