port: 25090
domain: sermon.mmx.kr
name: mmx monitor
fixedFont: false

notification:
  type: gmail
  id: cjng96@gmail.com
  pw:
  emails:
    - cjng96@gmail.com

servers:
  - name: kos
    url: kos.inertry.com
    id: cjng96
    monitor:
      # - cpu
      - load
      - mem
      - swap
      - disk
      - {
          type: app,
          name: eng,
          status: /work/eng/eng.st,
          saName: eng,
          memMax: 50m,
        }
      - { type: app, name: engFile, status: /work/efile/engFile.st }
      - { type: app, name: inerAuth, status: /work/iauth/inerAuth.st }
      - { type: app, name: inerUpdate, status: /work/iupdate/inerUpdate.st }
      - { type: app, name: inerLog, status: /work/ilog/inerLog.st }
      - { type: app, name: coll, status: /work/coll/coll.st }
      - { type: app, name: collPlus, status: /work/collplus/collPlus.st }
      - { type: app, name: collAdmin, status: /work/collAdmin/collAdmin.st }

  - name: m1
    url: nas.mmx.kr:13622
    id: cjng96
    monitor:
      # - cpu
      - load
      - mem
      - swap
      - disk
      - { type: app, name: engT, status: /work/engt/engt.st, saName: engt }
      - { type: app, name: engFileT, status: /work/efilet/engFileT.st }
      - { type: app, name: inerAuthT, status: /work/iautht/inerAuthT.st }
      - { type: app, name: inerUpdateT, status: /work/iupdatet/inerUpdateT.st }
      - { type: app, name: inerLogT, status: /work/ilogt/inerLogT.st }
      - { type: app, name: collT, status: /work/collt/collT.st }
      - { type: app, name: collPlusT, status: /work/collplust/collPlusT.st }

  - name: n2
    url: nas.mmx.kr:13522
    id: cjng96
    monitor:
      # - cpu
      - load
      - mem
      - swap
      - disk
      # - { type: mdadm, name: md0r, path: /dev/md0 }
      - newline
      - { type: disk, name: w, path: /mnt/data }
      # - { type: disk, name: md0, path: /media/md0 }
      # - { type: disk, name: bk, path: /media/bk }
