
servers:
  - name: tk1
    url: tk1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - mem
      - df

  - name: engs
    url: tk1.synapbook.com
    id: cjng96
    dkName: engs
    dkId: cjng96
    apps:
      - { name: eng, status: /tmp/eng.st }

  - name: nj1
    url: nj1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - mem
      - df
  
notification:
 - cjng96@gmail.com

port: 25090
