
servers:
  - name: tk1
    url: tk1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - mem
      - df

  - name: engs
    url: tk1.synapbook.com
    id: cjng96
    dkName: engs
    dkId: cjng96
    apps:
      - { name: eng, status: /tmp/eng.st }

notification:
 - cjng96@gmail.com

port: 25090
