
servers:
  - name: local
    url: localhost
    id: cjng96
    monitor:
      - type: docker

  - name: ipn
    url: localhost
    id: cjng96
    docker: ipn

notification:
 - cjng96@gmail.com

