
servers:
  - name: tk1
    url: tk1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk

  - name: engs
    url: tk1.synapbook.com
    id: cjng96
    dkName: engs
    dkId: cjng96
    monitor:
      - { type: app, name: engt, status: /tmp/engt.st }
      - { type: app, name: eng, status: /tmp/eng.st }

  - name: nj1
    url: nj1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
    
  - name: aws1
    url: aws1.synapbook.com
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
    
  - name: n2
    url: nas.mmx.kr:7022
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
    
notification:
 - cjng96@gmail.com

port: 25090
