port: 25090
domain: domain.com

notification:
  type: gmail
  id: cjng96@gmail.com
  pw:
  emails:
    - cjng96@gmail.com

servers:
  - name: local
    url: localhost
    id: cjng96
    monitor:
      - cpu
      - load
      - mem
      - swap
      - disk
      - { type: app, name: app, status: /work/app/app.st }
      - { type: app, name: appt, status: /work/appt/appt.st }
